### ISSUE TITLE
Form Save error

### ISSUE THREAD

**Issue by goutnet** [Mnkras/page_selector_attribute#2]
Hi,

I wanted to tell you I found this issue on 5.7:

when saving the form I get the following error on the console:

Uncaught Error: cannot call methods on dynatree prior to initialization; attempted to call method 'getTree'

This is preventing the rest of the javascript to run, and so the page attribute panel to close :/

Can you check this?

**Comment by Mnkras** [comment]
Its a c5 issue, its fixed in git

**Comment by Mnkras** [comment]
Just to further clarify (I was on my phone when I responded) the page selector widget was broken.

It would still save the value selected, but the page would be un-usable until refresh.
